include $(root)/src/Makefile.shared

LIBS += Reindeer

.PHONY: Reindeer 
Reindeer:
	$(MAKE) -C $(root)/src

.PHONY: Reindeer-clean
Reindeer-clean:
	$(MAKE) -C $(root)/src clean

INCLUDE_DIRS += $(root)/include
LIB_DIRS += $(root)/src
